config/routes.rb
Rails.application.routes.draw do
  resources :gnvls
  root 'gnvls#index'
  post 'gnvls/searching', to: 'gnvls#searching'
  post 'gnvls/search', to: 'gnvls#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gnvl.rb
class Gnvl < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gnvls_controller.rb
class GnvlsController < ApplicationController
  before_action :set_gnvl, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /gnvls
  # GET /gnvls.json
  def index
    @gnvls = Gnvl.limit(100).order('name asc')
  end

  # GET /gnvls/1
  # GET /gnvls/1.json
  def show
  end

  def search
    @par = params[:gnvls_name].to_s
    @gnvls = Gnvl.where(' similarity(name,?)>0.3',@par)

  end

  def searching
     #params.require(:gnvl).permit(:str)
     @res = "ALL Right"
     @par = params[:str].to_s
     #@res = Gnvl.where(" to_tsvector('russian',name) @@ to_tsquery('russian',?)",@par).limit(10)
     #if not @res.exists?
    #    @res = Gnvl.where(' similarity(name,?)>0.1',@par).limit(10)
     #end
     @res = Gnvl.connection.select_all('select id,name,owner,qntpack, similarity(name,\''+@par+'\')  as range from gnvls group by id,name,owner,qntpack having similarity(name,\''+@par+'\')>0.3 order by range desc')
# limit 50
     res=[]
     buf={}
     @res.each do |prod|
       buf={}
       buf[:id] = prod["id"]
       buf[:name] = prod["name"]
       buf[:owner] = prod["owner"]
       buf[:qntpack] = prod["qntpack"]
       res.push(buf)
     end

     render json: res
  end

  # GET /gnvls/new
  def new
    @gnvl = Gnvl.new
  end

  # GET /gnvls/1/edit
  def edit
  end

  # POST /gnvls
  # POST /gnvls.json
  def create
    @gnvl = Gnvl.new(gnvl_params)

    respond_to do |format|
      if @gnvl.save
        format.html { redirect_to @gnvl, notice: 'Gnvl was successfully created.' }
        format.json { render :show, status: :created, location: @gnvl }
      else
        format.html { render :new }
        format.json { render json: @gnvl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gnvls/1
  # PATCH/PUT /gnvls/1.json
  def update
    respond_to do |format|
      if @gnvl.update(gnvl_params)
        format.html { redirect_to @gnvl, notice: 'Gnvl was successfully updated.' }
        format.json { render :show, status: :ok, location: @gnvl }
      else
        format.html { render :edit }
        format.json { render json: @gnvl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gnvls/1
  # DELETE /gnvls/1.json
  def destroy
    @gnvl.destroy
    respond_to do |format|
      format.html { redirect_to gnvls_url, notice: 'Gnvl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gnvl
      @gnvl = Gnvl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gnvl_params
      params.require(:gnvl).permit(:gnvls_name,:mnn, :name, :lekform, :owner, :qntpack, :prc_wo_nds, :prc_first_pack, :n_py, :date_reg, :ean13, :atx, :level_nac_opt, :pred_opt_price, :level_nac_rozn, :pred_rozn_price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gnvls_helper.rb
module GnvlsHelper
end

app/views/gnvls/_form.html.erb
<%= form_for(gnvl) do |f| %>
  <% if gnvl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gnvl.errors.count, "error") %> prohibited this gnvl from being saved:</h2>

      <ul>
      <% gnvl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mnn %>
    <%= f.text_field :mnn %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :lekform %>
    <%= f.text_field :lekform %>
  </div>

  <div class="field">
    <%= f.label :owner %>
    <%= f.text_field :owner %>
  </div>

  <div class="field">
    <%= f.label :qntpack %>
    <%= f.text_field :qntpack %>
  </div>

  <div class="field">
    <%= f.label :prc_wo_nds %>
    <%= f.text_field :prc_wo_nds %>
  </div>

  <div class="field">
    <%= f.label :prc_first_pack %>
    <%= f.text_field :prc_first_pack %>
  </div>

  <div class="field">
    <%= f.label :n_py %>
    <%= f.text_area :n_py %>
  </div>

  <div class="field">
    <%= f.label :date_reg %>
    <%= f.text_field :date_reg %>
  </div>

  <div class="field">
    <%= f.label :ean13 %>
    <%= f.text_field :ean13 %>
  </div>

  <div class="field">
    <%= f.label :atx %>
    <%= f.text_field :atx %>
  </div>

  <div class="field">
    <%= f.label :level_nac_opt %>
    <%= f.text_field :level_nac_opt %>
  </div>

  <div class="field">
    <%= f.label :pred_opt_price %>
    <%= f.text_field :pred_opt_price %>
  </div>

  <div class="field">
    <%= f.label :level_nac_rozn %>
    <%= f.text_field :level_nac_rozn %>
  </div>

  <div class="field">
    <%= f.label :pred_rozn_price %>
    <%= f.text_field :pred_rozn_price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gnvls/edit.html.erb
<h1>Editing Gnvl</h1>

<%= render 'form', gnvl: @gnvl %>

<%= link_to 'Show', @gnvl %> |
<%= link_to 'Back', gnvls_path %>

app/views/gnvls/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>


  <%= form_tag("gnvls/", method: "get",class: "srch_frm") do %>
  <label for="q">Поиск по наименованию: </label>
  <input id="gnvls" name="gnvls_name" type="search"  />
    <div id="divId" style="display: none">

    </div>
    <% end %>
<!--</form> -->
<br>



<table class="table table-striped  fixtable">
  <thead class="fixhead">
    <tr>
      <th>МНН</th>
      <th>Наименование</th>
      <th>Лек.форма</th>
      <th>Изготовитель</th>
      <th>Кол.упак</th>
<!--      <th>Предельная цена без НДС</th>
      <th>Цена указана для первич. упаковки</th>
      <th>№ РУ</th>
      <th>"Дата регистрации цены(№ решения)"</th>
      <th>Штрих-код (EAN13)</th>
      <th>АТХ</th>
      <th>Уровень наценки, % Опт</th>
      <th>Предельная оптовая цена, руб. с НДС</th>
      <th>Уровень наценки, % Розн</th> -->
      <th>Предельная роз. цена, руб. с НДС</th>
    </tr>
</thead>

  <tbody class="fixbody">
    <% @gnvls.each do |gnvl| %>
      <tr  class='clickable-row' data-ref="<%= gnvl_path(gnvl) %>">
        <td><%= gnvl.mnn %></td>
        <td><%= gnvl.name %></td>
        <td><%= gnvl.lekform %></td>
        <td><%= gnvl.owner %></td>
        <td><%= gnvl.qntpack %></td>
<!--        <td><%= gnvl.prc_wo_nds %></td>
        <td><%= gnvl.prc_first_pack %></td>
        <td><%= gnvl.n_py %></td>
        <td><%= gnvl.date_reg %></td>
        <td><%= gnvl.ean13 %></td>
        <td><%= gnvl.atx %></td>
        <td><%= gnvl.level_nac_opt %></td>
        <td><%= gnvl.pred_opt_price %></td>
        <td><%= gnvl.level_nac_rozn %></td> -->
        <td><%= gnvl.pred_rozn_price %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>



</div>

app/views/gnvls/new.html.erb
<h1>New Gnvl</h1>

<%= render 'form', gnvl: @gnvl %>

<%= link_to 'Back', gnvls_path %>

app/views/gnvls/search.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<H2>Результаты поиска...</H2>

<table class="table table-striped  fixtable">
  <thead>
    <tr>
      <th>МНН</th>
      <th>Наименование</th>
      <th>Лек.форма</th>
      <th>Изготовитель</th>
      <th>Кол.упак</th>
<!--      <th>Предельная цена без НДС</th>
      <th>Цена указана для первич. упаковки</th>
      <th>№ РУ</th>
      <th>"Дата регистрации цены(№ решения)"</th>
      <th>Штрих-код (EAN13)</th>
      <th>АТХ</th>
      <th>Уровень наценки, % Опт</th>
      <th>Предельная оптовая цена, руб. с НДС</th>
      <th>Уровень наценки, % Розн</th> -->
      <th>Предельная розничная цена, руб. с НДС</th>

    </tr>
  </thead>

  <tbody>
    <% @gnvls.each do |gnvl| %>
      <tr  class='clickable-row' data-ref="<%= gnvl_path(gnvl) %>">
        <td><%= gnvl.mnn %></td>
        <td><%= gnvl.name %></td>
        <td><%= gnvl.lekform %></td>
        <td><%= gnvl.owner %></td>
        <td><%= gnvl.qntpack %></td>
<!--        <td><%= gnvl.prc_wo_nds %></td>
        <td><%= gnvl.prc_first_pack %></td>
        <td><%= gnvl.n_py %></td>
        <td><%= gnvl.date_reg %></td>
        <td><%= gnvl.ean13 %></td>
        <td><%= gnvl.atx %></td>
        <td><%= gnvl.level_nac_opt %></td>
        <td><%= gnvl.pred_opt_price %></td>
        <td><%= gnvl.level_nac_rozn %></td> -->
        <td><%= gnvl.pred_rozn_price %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>



</div>

app/views/gnvls/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<span class="noprint">
  <input type="button" value="Печать" onclick="print()"></input>
</span>
<p>
  <strong>МНН:</strong>
  <%= @gnvl.mnn %>
</p>

<p>
  <strong>Наименование:</strong>
  <%= @gnvl.name %>
</p>

<p>
  <strong>Лек.форма:</strong>
  <%= @gnvl.lekform %>
</p>

<p>
  <strong>Изготовитель:</strong>
  <%= @gnvl.owner %>
</p>

<p>
  <strong>Кол.упак:</strong>
  <%= @gnvl.qntpack %>
</p>

<p>
  <strong>Предельная цена без НДС:</strong>
  <%= @gnvl.prc_wo_nds %>
</p>

<p>
  <strong>Цена указана для первич. упаковки:</strong>
  <%= @gnvl.prc_first_pack %>
</p>

<p>
  <strong>№ РУ:</strong>
  <%= @gnvl.n_py %>
</p>

<p>
  <strong>Дата регистрации цены(№ решения):</strong>
  <%= @gnvl.date_reg %>
</p>

<p>
  <strong>Штрих-код (EAN13):</strong>
  <%= @gnvl.ean13 %>
</p>

<p>
  <strong>АТХ:</strong>
  <%= @gnvl.atx %>
</p>

<p>
  <strong>Уровень наценки, % Опт:</strong>
  <%= @gnvl.level_nac_opt %>
</p>

<p>
  <strong>Предельная оптовая цена, руб. с НДС:</strong>
  <%= @gnvl.pred_opt_price %>
</p>

<p>
  <strong>Уровень наценки, % Розн:</strong>
  <%= @gnvl.level_nac_rozn %>
</p>

<p>
  <strong>Предельная розничная цена, руб. с НДС:</strong>
  <%= @gnvl.pred_rozn_price %>
</p>


</div>

app/views/layouts/_header.html.erb
<div class="container">
<span class="noprint">
      <!-- Static navbar -->
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand" >
              <%= image_tag  "logo.png" %>
            </div>
          </div>
          <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
            <ul class="nav navbar-nav">
              <li><a href=<%= root_path %>>Обратно к поиску</a></li>
              <li><a href=<%= gnvls_path %>>Домой</a></li>
            </ul>

          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <!-- Main component for a primary marketing message or call to action -->
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class=""></li>
              <li data-target="#myCarousel" data-slide-to="1" class=""></li>
              <li data-target="#myCarousel" data-slide-to="2" class=""></li>
              <li data-target="#myCarousel" data-slide-to="3" class="active"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="item">
                <%= image_tag "57img.png" %>
                <div class="container">
                  <div class="carousel-caption">


                  </div>
                </div>
              </div>
              <div class="item">
                <%= image_tag "49img.png" %>
                <div class="container">
                  <div class="carousel-caption">

                  </div>
                </div>
              </div>
              <div class="item">
                <%= image_tag "58img.png" %>
                <div class="container">
                  <div class="carousel-caption">

                  </div>
                </div>
              </div>
              <div class="item active">
                <%= image_tag "60img.png" %>
                <div class="container">
                  <div class="carousel-caption">

                  </div>
                </div>
              </div>
            </div>

            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
</span>          
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Medika</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <style media='print' type='text/css'>
        .noprint {display: none;}
        body {background:#FFF; color:#000;}
        a {text-decoration: underline; color:#00F;}
        }
        </style>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>